[package]
name = "fishbot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
poise = "0.5.5"
shuttle-poise = "0.34.0"
shuttle-runtime = "0.34.0"
shuttle-secrets = "0.34.0"
tracing = "0.1.37"
tokio = "1.28.2"