[package]
name = "fishbot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
axum = "0.6.4"
hyper = "0.14.24"
poise = "0.5.2"
serde = "1.0"
shuttle-poise = "0.35.0"
shuttle-runtime = "0.35.0"
shuttle-secrets = "0.35.0"
tokio = "1.28.2"